name: Auto Update README

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 3 hours
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure you are using the correct token for authentication

      - name: Set up Git
        run: |
          git config --global user.name 'avayyyyyyy'
          git config --global user.email 'jabhi465@gmail.com'

      - name: Run update script
        run: |
          chmod +x update_readme.sh
          ./update_readme.sh

      - name: Check for changes and push
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated update at $(date -u '+%Y-%m-%d %H:%M:%S') UTC"
            git push origin main
          else
            echo "No new changes to commit."
          fi
