name: Auto Update README

on:
  schedule:
    - cron: "0 */3 * * *" # Runs every 3 hours
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'avayyyyyyy'
          git config --global user.email 'jabhi465@gmail.com'

      - name: Run update script
        run: |
          chmod +x update_readme.sh
          ./update_readme.sh
          echo "Update script executed"

      - name: Authenticate with GitHub
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git remote set-url origin https://avayyyyyyy:${{ secrets.ACTIONS_PAT }}@github.com/avayyyyyyy/avayyyyyyy.git
          echo "GitHub authentication configured"

      - name: Check for changes and push
        run: |
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated update at $(date -u '+%Y-%m-%d %H:%M:%S') UTC"
            git push -f origin main
          else
            echo "No changes to commit"
          fi
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
